spring:
  profiles:
    group:
      "dev": "dev, common"
      "prod": "prod, common, awsPostgres"
---
spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    hibernate:
      ddl-auto: update
      #format_sql: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rain_dev
    username: yunhyunjun
    password:
    connection-timeout: 3000
    maximum-pool-size: 50
    minimum-idle: 10
    idle-timeout: 60000

logging:
  level:
    root: info
    com.exithere.rain: debug
    org.springframework: info

---
spring:
  config:
    activate:
      on-profile: "prod"

  jpa:
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/awc
    username: postgres
    password:
    connection-timeout: 3000
    maximum-pool-size: 50
    minimum-idle: 10
    idle-timeout: 60000

logging:
  level:
    root: info
    com.exithere.rain: info
    org.springframework: info

---
spring:
  config:
    activate:
      on-profile: "common"

server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: false
